version: '3'

services:
  postgres:
    restart: ${DOCKER_RESTART_POLICY-on-failure}
    image: postgres:10.1-alpine
    environment: &pg_env
      POSTGRES_USER: ${SLACK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SLACK_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SLACK_POSTGRES_DB}
    volumes:
      - slack_postgres_data/:/var/lib/postgresql/data

  db-migration:
    restart: on-failure
    image: woost/db-migration:${WUST_VERSION-latest}-slack
    environment:
      <<: *pg_env
    depends_on:
      - postgres

  slack:
    restart: ${DOCKER_RESTART_POLICY-on-failure}
    image: woost/slack:${WUST_VERSION-latest}
    environment:
      WUST_SLACK_APP_TOKEN: ${WUST_SLACK_APP_TOKEN} # TODO: do not use static token in production
      WUST_USER: ${WUST_USER}
      WUST_PASSWORD: ${WUST_PASSWORD}
      WUST_HOSTNAME: ${WUST_HOSTNAME}
      WUST_PORT: ${WUST_PORT}
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:${WUST_SLACK_PORT-8080}:8080"

volumes:
    slack_postgres_data:
