sudo: required

services: docker
language: scala
jdk: oraclejdk8
node_js: 9

branches:
  only:
  - master
  - /release-.*/

# TODO: use https://github.com/dwijnand/sbt-travisci
script:
    - sbt scalafmt
    - git diff

cache:
  yarn: true
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.ivy2/local
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
  - $HOME/.cache/coursier

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2       -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
