sudo: required

services: docker
language: scala
jdk: oraclejdk8
node_js: 9

branches:
  only:
  - master
  - travis
  - /rc-.*/

# TODO: use https://github.com/dwijnand/sbt-travisci
script:
    - set -e
    - ci/build-unit-test
    - ci/build-artifacts
    - ci/test-postgres
    - ci/test-integration
    - set +e

after_success:
    - set -e
    - ci/publish-artifacts
    # - sbt coverageAggregate coveralls
    # - sbt coverageAggregate # Must be called separately for multi project projects (https://github.com/scoverage/sbt-scoverage#multi-project-reports)
    # - sbt coveralls #See https://github.com/scoverage/sbt-coveralls/issues/104
    - set +e

cache:
  yarn: true
  directories:
  - .yarn-offline-cache
  - $HOME/.ivy2/cache
  - $HOME/.ivy2/local
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
  - $HOME/.cache/coursier

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2       -name "ivydata-*.properties" -delete
- find $HOME/.sbt        -name "*.lock"               -delete
