sudo: required

services: docker
language: scala
jdk: oraclejdk8
node_js: 9

branches:
  only:
  - master

# before_install:
# - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
#     eval "$(ssh-agent -s)";
#     openssl aes-256-cbc -K $encrypted_b3beb67678c9_key -iv $encrypted_b3beb67678c9_iv -in ./travis/travis-\>github.enc -out travis-\>github -d;
#     chmod 600 $TRAVIS_BUILD_DIR/travis-\>github;
#     ssh-add $TRAVIS_BUILD_DIR/travis-\>github;
# fi

//TODO: use https://github.com/dwijnand/sbt-travisci
script:
    - set -e
    - .travis/build
    - .travis/integration-tests
    - set +e

after_success:
    - set -e
    - .travis/publish-docker
    # - sbt coverageAggregate # Must be called separately for multi project projects (https://github.com/scoverage/sbt-scoverage#multi-project-reports)
    # - sbt coveralls #See https://github.com/scoverage/sbt-coveralls/issues/104
    - .travis/publish-scaladoc.sh
    - set +e

cache:
  yarn: true
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.ivy2/local
  - $HOME/.sbt/boot/

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2       -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
