sudo: required

services: docker
language: scala
jdk: oraclejdk8
node_js: 7

install:
    - set -e
    # - .travis/install
    - set +e

script:
    - set -e
    - .travis/build
    - .travis/integration-tests
    - set +e

after_success:
    - set -e
    - .travis/publish-docker
    - sbt coverageAggregate coveralls
    - set +e

cache:
  yarn: true
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.ivy2/local
  - $HOME/.sbt/boot/

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2       -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
