version: 0.2

phases:
  # install:
    # runtime-versions:
      # java: openjdk11
      # docker: 2.2
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ci/build-unit-test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    # - target/messageUtil-1.0.jar
