version: 0.2

phases:
  install:
    runtime-versions:
      docker: 2.2
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ci/build-unit-test
      - ci/build-docker
      # - ci/test-postgres
      # - ci/test-integration
      - ci/publish-docker
  post_build:
    commands:
      - echo Build completed on `date`
