version: '2'

services:

  ####################
  # wust
  ####################
  wust-postgres:
    restart: on-failure
    image: postgres:10.1-alpine
    environment: &pg_env
      POSTGRES_USER: 'wust'
      POSTGRES_PASSWORD: ${WUST_POSTGRES_PASSWORD}
      POSTGRES_DB: 'wust'
    volumes:
      - wust_pg_data/:/var/lib/postgresql/data

  wust-db-migration:
    restart: on-failure
    image: woost/db-migration:wust
    environment:
      <<: *pg_env
    depends_on:
      - wust-postgres

  wust-core:
    restart: on-failure
    image: woost/core:latest
    environment:
      <<: *pg_env
      POSTGRES_HOSTNAME: "postgres"
      WUST_AUTH_SECRET: ${WUST_AUTH_SECRET}
      WUST_EMAIL_ADDRESS: ${WUST_EMAIL_ADDRESS}
      WUST_SMTP_ENDPOINT: ${WUST_SMTP_ENDPOINT}
      WUST_SMTP_USER: ${WUST_SMTP_USER}
      WUST_SMTP_PASS: ${WUST_SMTP_PASS}
    depends_on:
      - wust-postgres
    ports:
      - "127.0.0.1:9000:8080"

  wust-web:
    restart: on-failure
    image: woost/web:latest
    ports:
      - "127.0.0.1:9001:80"

  ####################
  # slack
  ####################
  slack-app:
    restart: on-failure
    image: woost/slack:latest
    environment:
      WUST_SLACK_TOKEN: ${WUST_SLACK_TOKEN} # TODO: do not use static token in production
      WUST_USER: ${WUST_USER}
      WUST_PASSWORD: ${WUST_PASSWORD}
      WUST_HOSTNAME: "wust-core"
    depends_on:
      - wust-core
    ports:
      - "127.0.0.1:9010:9010"

  ####################
  # gitter
  ####################
  gitter-app:
    restart: on-failure
    image: woost/gitter:latest
    environment:
      WUST_GITTER_TOKEN: ${WUST_GITTER_TOKEN} # TODO: do not use static token in production
      WUST_USER: ${WUST_USER}
      WUST_PASSWORD: ${WUST_PASSWORD}
      WUST_HOSTNAME: "wust-core"
    depends_on:
      - wust-core
    ports:
      - "127.0.0.1:9020:9020"

  ####################
  # github
  ####################
  github-redis:
    restart: on-failure
    image: redis:4.0-alpine

  github-app:
    restart: on-failure
    image: woost/github:latest
    environment:
      WUST_GITHUB_TOKEN: ${WUST_GITHUB_TOKEN} # TODO: do not use static token in production
      WUST_USER: ${WUST_USER}
      WUST_PASSWORD: ${WUST_PASSWORD}
      WUST_HOSTNAME: "wust-core"
    volumes:
      - github_redis_data:/data
    depends_on:
      - wust-core
      - github-redis
    ports:
      - "127.0.0.1:54321:54321"

volumes:
  wust_pg_data:
  github_redis_data:
