version: '2'

services:
  postgres:
    image: postgres:10.1-alpine
    environment: &pg_env
      POSTGRES_USER: 'wust'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'wust'
  db-migration:
    image: woost/wust2.db-migration
    environment:
      <<: *pg_env
  wust:
    image: woost/wust2
    environment:
      <<: *pg_env
      POSTGRES_HOSTNAME: "postgres"
      WUST_AUTH_SECRET: ${WUST_AUTH_SECRET}
      WUST_EMAIL_ADDRESS: ${WUST_EMAIL_ADDRESS}
      WUST_SMTP_ENDPOINT: ${WUST_SMTP_ENDPOINT}
      WUST_SMTP_USER: ${WUST_SMTP_USER}
      WUST_SMTP_PASS: ${WUST_SMTP_PASS}
  nginx:
    image: woost/wust2.nginx
  slack-app:
    image: woost/wust2.slack-app
    environment:
      WUST_SLACK_TOKEN: ${WUST_SLACK_TOKEN} # TODO: do not use static token in production
      WUST_USER: ${WUST_USER}
      WUST_PASSWORD: ${WUST_PASSWORD}
      WUST_HOSTNAME: "wust"
