version: '3'

services:
  postgres:
    restart: ${DOCKER_RESTART_POLICY-on-failure}
    image: postgres:11.5-alpine

    # https://pgtune.leopard.in.ua
    # DB Version: 10
    # OS Type: linux
    # DB Type: web
    # Total Memory (RAM): 16 GB
    # CPUs num: 8
    # Data Storage: ssd
    command: postgres -c "max_connections=200" -c "shared_buffers=4GB" -c "effective_cache_size=12GB" -c "maintenance_work_mem=1GB" -c "checkpoint_completion_target=0.7" -c "wal_buffers=16MB" -c "default_statistics_target=100" -c "random_page_cost=1.1" -c "effective_io_concurrency=200" -c "work_mem=5242kB" -c "min_wal_size=1GB" -c "max_wal_size=2GB" -c "max_worker_processes=8" -c "max_parallel_workers_per_gather=4" -c "max_parallel_workers=8" 



    environment: &pg_env
      POSTGRES_HOSTNAME: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_USER: 'wust'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'wust'
    volumes:
      - core_postgres_data/:/var/lib/postgresql/data

  db-migration:
    restart: on-failure
    image: woost/db-migration:${WUST_VERSION-latest}-core
    environment:
      <<: *pg_env
    depends_on:
      - postgres

  core:
    restart: on-failure
    image: woost/core:${WUST_VERSION-latest}
    environment:
      <<: *pg_env
      POSTGRES_HOSTNAME: "postgres"
      WUST_HOSTNAME: ${WUST_HOSTNAME}
      WUST_AUTH_SECRET: ${WUST_AUTH_SECRET}
      WUST_EMAIL_ADDRESS: ${WUST_EMAIL_ADDRESS}
      WUST_SMTP_ENDPOINT: ${WUST_SMTP_ENDPOINT}
      WUST_SMTP_USER: ${WUST_SMTP_USER}
      WUST_SMTP_PASS: ${WUST_SMTP_PASS}
      WUST_WEB_PUSH_SUBJECT: ${WUST_WEB_PUSH_SUBJECT}
      WUST_WEB_PUSH_PUBLIC_KEY: ${WUST_WEB_PUSH_PUBLIC_KEY}
      WUST_WEB_PUSH_PRIVATE_KEY: ${WUST_WEB_PUSH_PRIVATE_KEY}
      WUST_AWS_ACCESS_KEY: ${WUST_AWS_ACCESS_KEY}
      WUST_AWS_SECRET_KEY: ${WUST_AWS_SECRET_KEY}
      WUST_AWS_UPLOAD_BUCKET: ${WUST_AWS_UPLOAD_BUCKET}
      WUST_AWS_REGION: ${WUST_AWS_REGION}
      WUST_LOGSTASH_URL: ${WUST_LOGSTASH_URL}
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:${WUST_CORE_PORT-8080}:8080"
    volumes:
      - core_logs/:/app/logs

volumes:
  core_postgres_data:
  core_logs:
